Module: ServerlessLink
Version: 1.0
Description: Link shortening app
Requires:

  - Module: LambdaSharpS3PackageLoader
    Version: 0.5-WIP

Outputs:

  - Export: EventsJsonArchive
    Value: !GetAtt DynamoDBTable.Arn

Entries:

  - Parameter: RootDomainName
    Description: The name of the domain for the serverless application
    Default: mindtouch.mx

  - Variable: SubDomainName
    Value: !Sub "link.${RootDomainName}"

  - Variable: RegionWebsiteEndpoint
    Value: s3-website-us-east-1.amazonaws.com

  # - Resource: AssertUsEast1
  #   Type: LambdaSharp::Assert
  #   Condition: ApiCertifcateArn::Created
  #   Properties:
  #     Expression: !Ref AWS::Region
  #     StringEquals: us-east-1
  #     FailureReason: "region must be us-east-1"

  - Variable: Website
    Entries:

      - Resource: Bucket
        Type: AWS::S3::Bucket
        Properties:
          WebsiteConfiguration:
            IndexDocument: index.html
        Entries:

          - Resource: Policy
            Type: AWS::S3::BucketPolicy
            Properties:
              Bucket: !Ref Website::Bucket
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Sid: WebsiteBucketPublicReadAccess
                    Effect: Allow
                    Principal: "*"
                    Action:
                      - s3:GetObject
                    Resource: !Sub "${Website::Bucket.Arn}/*"

      - Package: ContentPackage
        Files: public/

      - Resource: CopyContentToBucket
        Type: LambdaSharp::S3::Package
        # Type: LambdaSharp::S3::UnzipPackage
        Properties:
          SourceBucketName: !Ref DeploymentBucketName
          SourcePackageKey: !Ref Website::ContentPackage
          DestinationBucketName: !Ref Website::Bucket
          DestinationKeyPrefix: ""

      # - Resource: WriteConfigFile
      #   Type: LambdaSharp::S3::WriteFile
      #   Properties:
      #     DestinationBucketName: !Ref Website::Bucket
      #     DestinationKey: js/config.js
      #     ContentType: json|yaml
      #     Contents:
      #       "window._config":
      #           api:
      #             invokeUrl: !Ref Api::DomainName
      #             scheme: https
      #     Contents: !Join
      #       - ""
      #       - - "window._config = {"
      #         - "  api: {"
      #         - !Sub "    invokeUrl: \"${Api::DomainName}\""
      #         - "  }"
      #         - "}"

      - Resource: DomainRecordSet
        Type: AWS::Route53::RecordSetGroup
        Properties:
          HostedZoneName: !Sub "${RootDomainName}."
          RecordSets:
            - AliasTarget:
                DNSName: !GetAtt Website::CloudfrontDistribution.DomainName
                HostedZoneId: Z2FDTNDATAQYW2  # This is the default hosted zone id for CloudFront
              Name: !Ref SubDomainName
              Type: A

      # Certificate for cloud front distribution.
      # This must be approved by admin for the CF template to be successful
      - Resource: Certificate
        Type: AWS::CertificateManager::Certificate
        Properties:
          ValidationMethod: DNS
          DomainName: !Ref SubDomainName

      - Resource: CloudfrontDistribution
        Type: AWS::CloudFront::Distribution
        Properties:
          DistributionConfig:
            Aliases:
              - !Ref SubDomainName
            DefaultCacheBehavior:
              AllowedMethods:
                - GET
                - HEAD
              ForwardedValues:
                QueryString: true
              TargetOriginId: WebsiteBucket
              ViewerProtocolPolicy: redirect-to-https
            Enabled: true
            Origins:
              - CustomOriginConfig:
                  HTTPPort: 80
                  HTTPSPort: 443
                  OriginProtocolPolicy: http-only
                DomainName: !Sub "${Website::Bucket}.${RegionWebsiteEndpoint}"
                Id: WebsiteBucket
            PriceClass: PriceClass_100
            ViewerCertificate:
              AcmCertificateArn: !Ref Website::Certificate
              MinimumProtocolVersion: TLSv1
              SslSupportMethod: sni-only

  - Variable: Api
    Entries:

      - Variable: DomainName
        Value: !Sub "m.${SubDomainName}"

      - Resource: DomainRecordSet
        Type: AWS::Route53::RecordSetGroup
        Properties:
          HostedZoneName: !Sub "${RootDomainName}."
          RecordSets:
            - AliasTarget:
                DNSName: !GetAtt Api::GatewayDomain.DistributionDomainName
                HostedZoneId: Z1UJRXOUMOOFQ8 # Z2FDTNDATAQYW2  # This is the default hosted zone id for CloudFront
              Name: !Ref Api::DomainName
              Type: A

      - Resource: DomainMapping
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
          BasePath: ""
          Stage: !Ref Module::RestApi::Stage
          DomainName: !Ref Api::GatewayDomain
          RestApiId: !Ref Module::RestApi

      # Certificate for cloud front distribution.
      # This must be approved by admin for the CF template to be successful
      - Resource: Certificate
        Type: AWS::CertificateManager::Certificate
        Properties:
          ValidationMethod: DNS
          DomainName: !Ref Api::DomainName

      - Resource: GatewayDomain
        Type: AWS::ApiGateway::DomainName
        Properties:
          # Use if you want it to create a cloudfront distribution
          # CertificateArn: !Ref Api::Certificate
          # EndpointConfiguration:
          #   Types:
          #     - EDGE
          RegionalCertificateArn: !Ref Api::Certificate
          EndpointConfiguration:
            Types:
            - REGIONAL
          DomainName: !Ref Api::DomainName

  - Resource: DynamoDBTable
    Scope: "*"
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LinkId
          AttributeType: S
      KeySchema:
        - AttributeName: LinkId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ExpirationTime
        Enabled: true

  - Function: CreateLink
    Description: TODO - update CreateLink description
    Memory: 256
    Timeout: 30
    Sources:
      - Api: POST:/

  - Function: ResolveLink
    Description: TODO - update ResolveLink description
    Memory: 256
    Timeout: 30
    Sources:
      - Api: GET:/{id}
