iamRoleStatements:
  - Effect: "Allow"
    Action:
      - sns:Publish
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-error-topic-arn"
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Query
    Resource:
      - Fn::GetAtt: [ DynamoDBTable, Arn ]
      - Fn::Join: ["/", [ Fn::GetAtt: [DynamoDBTable, Arn], "index", "*"]]

environment:
  SNS_ERROR_TOPIC:
    Fn::ImportValue: "${self:custom.stageName}-error-topic-arn"

custom:
  stageName: ${opt:stage, self:provider.stage}

deadLetterQueue:
  Fn::ImportValue: "${self:custom.stageName}-error-topic-arn"
