iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
      - dynamodb:Query
    Resource:
      - Fn::GetAtt: [ DynamoDBTable, Arn ]
      - Fn::Join: ["/", [ Fn::GetAtt: [DynamoDBTable, Arn], "index", "*"]]
  - Effect: Allow
    Action:
      - sqs:SendMessageBatch
      - sqs:SendMessage
    Resource:
      - Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"

custom:
  stageName: ${opt:stage, self:provider.stage}

deadLetterQueue:
  Fn::ImportValue: "${self:custom.stageName}-dead-letter-queue-arn"
